
sELECT*FROM ORDERS
--CÂU 1:
SELECT 
    c.CUSTOMER_ID, 
    c.NAME,
    COUNT(DISTINCT O.ORDER_ID)
FROM 
    CUSTOMERS c
INNER JOIN 
    ORDERS o 
ON 
    c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE 
    o.STATUS = 'Shipped'
GROUP BY 
    c.CUSTOMER_ID, 
    c.NAME
HAVING 
    COUNT(o.ORDER_ID) > 3;

--CÂU 2:
SELECT 
    C.CUSTOMER_ID, 
    C.NAME,
    COUNT(O.ORDER_ID) AS CANCEL_ORDER
FROM 
    CUSTOMERS C
INNER JOIN 
    ORDERS O
ON 
    C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE 
    O.STATUS = 'Canceled'
    AND EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY 
    C.CUSTOMER_ID, 
    C.NAME
HAVING 
    COUNT(O.ORDER_ID) > 2;

--CÂU 3:
SELECT 
    C.CUSTOMER_ID, 
    C.NAME,
    SUM(OI.QUANTITY) AS TOTAL_PRODUCTS
FROM 
    CUSTOMERS C
INNER JOIN 
    ORDERS O 
ON 
    C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN 
    ORDER_ITEMS OI 
ON 
    O.ORDER_ID = OI.ORDER_ID
GROUP BY 
    C.CUSTOMER_ID, 
    C.NAME
HAVING 
    SUM(OI.QUANTITY) > 10;

--Câu 4:
SELECT 
    C.CUSTOMER_ID, 
    C.NAME,
    O.ORDER_ID,
    O.ORDER_DATE,
    SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM 
    CUSTOMERS C
INNER JOIN 
    ORDERS O 
ON 
    C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN 
    ORDER_ITEMS OI 
ON 
    O.ORDER_ID = OI.ORDER_ID
WHERE 
    O.STATUS = 'Pending'
    AND O.ORDER_DATE > TO_DATE('2017-02-10', 'YYYY-MM-DD')
GROUP BY 
    C.CUSTOMER_ID, 
    C.NAME, 
    O.ORDER_ID, 
    O.ORDER_DATE
HAVING 
    SUM(OI.QUANTITY) > 50
ORDER BY 
    C.CUSTOMER_ID;

--CÂU 5:
SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME,
    COALESCE(SUM(OI.QUANTITY), 0) AS TOTAL_QUANTITY_SOLD,
    COALESCE(SUM(OI.UNIT_PRICE * OI.QUANTITY), 0) AS TOTAL_SALES_VALUE,
    ROUND(COALESCE(AVG(OI.UNIT_PRICE * OI.QUANTITY), 0),2) AS AVG_SALES_VALUE
FROM 
    PRODUCTS P
LEFT JOIN 
    ORDER_ITEMS OI 
ON 
    P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME
ORDER BY 
    P.PRODUCT_ID;

--CÂU 6
SELECT 
    P.PRODUCT_NAME,
    COUNT(O.ORDER_ID) AS TOTAL_ORDER
FROM 
    PRODUCTS P
INNER JOIN 
    ORDER_ITEMS OI 
ON 
    P.PRODUCT_ID = OI.PRODUCT_ID
INNER JOIN 
    ORDERS O 
ON 
    O.ORDER_ID = OI.ORDER_ID
WHERE EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_ORDER DESC
FETCH FIRST 10 ROWS ONLY;

--cÂU 7
SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME,
    SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM 
    PRODUCTS P
INNER JOIN 
    ORDER_ITEMS OI 
ON 
    P.PRODUCT_ID = OI.PRODUCT_ID
INNER JOIN 
    ORDERS O 
ON 
    OI.ORDER_ID = O.ORDER_ID
WHERE 
    (O.STATUS = 'Canceled' OR O.STATUS = 'Pending')
    AND O.ORDER_DATE > TO_DATE('2016-10-02', 'YYYY-MM-DD')
GROUP BY 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME
ORDER BY 
    TOTAL_QUANTITY DESC
FETCH FIRST 20 ROWS ONLY;

--CÂU 8
--CÂU 9
SELECT 
    PC.CATEGORY_NAME,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDER
FROM 
    PRODUCTS P
INNER JOIN 
    ORDER_ITEMS OI 
ON 
    P.PRODUCT_ID = OI.PRODUCT_ID
INNER JOIN 
    PRODUCT_CATEGORIES PC 
ON 
    PC.CATEGORY_ID = p.category_id
INNER JOIN 
    ORDERS O 
ON 
    OI.ORDER_ID = O.ORDER_ID
WHERE o.order_date BETWEEN TO_DATE('01/01/2017','DD/MM/YYYY') AND TO_DATE('31/3/2017','DD/MM/YYYY')
GROUP BY  pc.category_name
ORDER BY pc.category_name

--Câu 10
SELECT  P.PRODUCT_ID,
        P.PRODUCT_NAME
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
WHERE I.QUANTITY = 0 OR I.QUANTITY IS NULL

--CÂU 11
SELECT  P.PRODUCT_ID,
        P.PRODUCT_NAME,
        PC.CATEGORY_NAME
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN 
    PRODUCT_CATEGORIES PC 
ON 
    PC.CATEGORY_ID = p.category_id 
WHERE I.QUANTITY = 0 OR I.QUANTITY IS NULL

--CÂU 12
SELECT  W.WAREHOUSE_NAMES,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(DISTINCT I.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN WAREHOUSES W
ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
GROUP BY P.PRODUCT_ID,
        P.PRODUCT_NAME,
        W.WAREHOUSE_NAMES
ORDER BY 
        W.WAREHOUSE_NAMES,
        P.PRODUCT_ID
        

--CÂU 13
SELECT  
        W.WAREHOUSE_NAMES,
        L.ADDRESS,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(DISTINCT I.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN WAREHOUSES W
ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
INNER JOIN LOCATIONS L
ON L.LOCATION_ID = W.LOCATION_ID
GROUP BY L.ADDRESS, 
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        W.WAREHOUSE_NAMES
ORDER BY 
        W.WAREHOUSE_NAMES,
        P.PRODUCT_ID

--CÂU 14
SELECT  
        W.WAREHOUSE_NAMES,
        L.ADDRESS,
        COU.COUNTRY_NAME,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(DISTINCT I.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN WAREHOUSES W
ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
INNER JOIN LOCATIONS L
ON L.LOCATION_ID = W.LOCATION_ID
INNER JOIN COUNTRIES COU
ON COU.COUNTRY_ID = L.COUNTRY_ID
GROUP BY L.ADDRESS, 
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        W.WAREHOUSE_NAMES,
        COU.COUNTRY_NAME
ORDER BY 
        W.WAREHOUSE_NAMES,
        P.PRODUCT_ID

--CÂU 15
SELECT  
        W.WAREHOUSE_NAMES,
        L.ADDRESS,
        COU.COUNTRY_NAME,
        R.REGION_NAME,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(DISTINCT I.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN WAREHOUSES W
ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
INNER JOIN LOCATIONS L
ON L.LOCATION_ID = W.LOCATION_ID
INNER JOIN COUNTRIES COU
ON COU.COUNTRY_ID = L.COUNTRY_ID
INNER JOIN REGIONS R
ON R.REGION_ID = COU.REGION_ID
GROUP BY L.ADDRESS, 
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        W.WAREHOUSE_NAMES,
        COU.COUNTRY_NAME,
        R.REGION_NAME
ORDER BY 
        W.WAREHOUSE_NAMES,
        P.PRODUCT_ID

--CÂU 16
SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    W.WAREHOUSE_NAMES, 
    SUM(I.QUANTITY) AS TOTAL_QUANTITY
FROM 
    PRODUCTS P
INNER JOIN 
    INVENTORIES I 
ON 
    P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN 
    WAREHOUSES W 
ON 
    I.WAREHOUSE_ID = W.WAREHOUSE_ID
GROUP BY 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    W.WAREHOUSE_NAMES
ORDER BY 
    TOTAL_QUANTITY DESC
FETCH FIRST 100 ROWS ONLY;

--CÂU 17
SELECT  
        W.WAREHOUSE_NAMES,
        COU.COUNTRY_NAME,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(DISTINCT I.QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS P
INNER JOIN INVENTORIES I
ON P.PRODUCT_ID = I.PRODUCT_ID
INNER JOIN WAREHOUSES W
ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
INNER JOIN LOCATIONS L
ON L.LOCATION_ID = W.LOCATION_ID
INNER JOIN COUNTRIES COU
ON COU.COUNTRY_ID = L.COUNTRY_ID
INNER JOIN REGIONS R
ON R.REGION_ID = COU.REGION_ID
GROUP BY L.ADDRESS, 
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        W.WAREHOUSE_NAMES,
        COU.COUNTRY_NAME,
        R.REGION_NAME
ORDER BY 
       TOTAL_QUANTITY 
FETCH FIRST 100 ROWS ONLY;


--CÂU 18
SELECT 
    COALESCE(E.EMPLOYEE_ID, 0) AS EMPLOYEE_ID, 
    COALESCE(E.FIRST_NAME || ' ' || E.LAST_NAME, 'Unknown') AS FULL_NAME,  
    SUM(OI.UNIT_PRICE * OI.QUANTITY) AS TOTAL_REVENUE
FROM 
    EMPLOYEES E
INNER JOIN 
    ORDERS O 
ON 
    E.EMPLOYEE_ID = O.SALESMAN_ID
INNER JOIN 
    ORDER_ITEMS OI 
ON 
    O.ORDER_ID = OI.ORDER_ID
GROUP BY 
    E.EMPLOYEE_ID, 
    E.FIRST_NAME, 
    E.LAST_NAME
ORDER BY 
    TOTAL_REVENUE DESC
FETCH FIRST 10 ROWS ONLY;

--Câu 19
SELECT 
    E.EMPLOYEE_ID, 
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME, 
    EXTRACT(YEAR FROM O.ORDER_DATE) AS ORDER_YEAR, 
    COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM 
    EMPLOYEES E
INNER JOIN 
    ORDERS O 
ON 
    E.EMPLOYEE_ID = O.SALESMAN_ID
WHERE 
    EXTRACT(YEAR FROM O.ORDER_DATE) IN (2016, 2017)
GROUP BY 
    E.EMPLOYEE_ID, 
    E.FIRST_NAME, 
    E.LAST_NAME, 
    EXTRACT(YEAR FROM O.ORDER_DATE)
ORDER BY 
    ORDER_YEAR, 
    E.EMPLOYEE_ID;

--Câu 20
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULLNAME,
    EXTRACT(MONTH FROM O.ORDER_DATE) AS ORDER_MONTH,
    COUNT(O.ORDER_ID) AS TOTAL_ORDER_CANCELED
FROM
    EMPLOYEES E
INNER JOIN 
    ORDERS O 
ON 
    E.EMPLOYEE_ID = O.SALESMAN_ID
WHERE
    EXTRACT(YEAR FROM O.ORDER_DATE) = 2017
GROUP BY
    E.EMPLOYEE_ID, 
    E.FIRST_NAME, 
    E.LAST_NAME,
    EXTRACT(MONTH FROM O.ORDER_DATE)
ORDER BY
    ORDER_MONTH,
    E.EMPLOYEE_ID


--CÂU 21
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULLNAME,
    SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM
    EMPLOYEES E
INNER JOIN 
    ORDERS O 
ON 
    E.EMPLOYEE_ID = O.SALESMAN_ID
INNER JOIN
    ORDER_ITEMS OI
ON 
    OI.ORDER_ID = O.ORDER_ID
WHERE
    O.ORDER_DATE BETWEEN TO_DATE('2016-01-01', 'YYYY-MM-DD') AND TO_DATE('2016-04-30', 'YYYY-MM-DD')
GROUP BY
    E.EMPLOYEE_ID, 
    E.FIRST_NAME, 
    E.LAST_NAME
ORDER BY
    TOTAL_QUANTITY




























