--2.1 CÁC YÊU CẦU TẠO DỮ LIỆU

--CÂU 1
ALTER TABLE THAI_SANPHAM
ADD GHICHU VARCHAR(20);

--CÂU 2
ALTER TABLE THAI_KHACHHANG
ADD LOAIKH NUMERIC;

--CÂU 3
ALTER TABLE THAI_SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

--CÂU 4
ALTER TABLE THAI_SANPHAM
DROP COLUMN GHICHU;

--CÂU 5
ALTER TABLE THAI_KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20);

--CÂU 6
ALTER TABLE THAI_CTHD
ALTER COLUMN SOHD NUMERIC NOT NULL;

--2.2 CÁC YÊU CẦU TRUY VẤN DỮ LIỆU

--CÂU 1
SELECT	MASP
		,TENSP
FROM THAI_SANPHAM
WHERE 
	NUOCSX = 'Trung Quoc'

--CÂU 2
SELECT	MASP
		,TENSP
FROM THAI_SANPHAM
WHERE
	DVT in ( 'Cay', 'quyen')

--CÂU 3
SELECT	
	MASP
	,TENSP
FROM THAI_SANPHAM
WHERE
	MASP LIKE 'B%01'

--CÂU 4
SELECT
	MASP
	,TENSP
FROM THAI_SANPHAM
WHERE
	NUOCSX = 'Trung Quoc'
 AND GIA BETWEEN 30000 AND 40000

 --CÂU 5
SELECT
	MASP
	,TENSP
FROM THAI_SANPHAM
WHERE 
	NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan'
 AND GIA BETWEEN 30000 AND 40000

 --CÂU 6
SELECT
	SOHD
	,TRIGIA
FROM THAI_HOADON
WHERE NGHD IN ( '2007-01-01','2007-01-02')

 --CÂU 7
SELECT
	SOHD
	,TRIGIA
	,NGHD
FROM THAI_HOADON
WHERE YEAR(NGHD) = 2007 AND MONTH(NGHD) = 1
ORDER BY NGHD ASC, TRIGIA DESC

 --CÂU 8
SELECT
	*
FROM  THAI_KHACHHANG KH
JOIN THAI_HOADON HD
ON KH.MAKH=HD.MAKH
WHERE NGHD = '2007-01-01'

 --Câu 9
SELECT 
	HD.SOHD
	,HD.TRIGIA
FROM THAI_HOADON HD
JOIN THAI_NHANVIEN NV
ON HD.MANV = HD.MANV
WHERE NV.HOTEN = 'Nguyen Van B'
	AND HD.NGHD = '2006-10-28'

--CÂU 10
SELECT
	SP.MASP
	,SP.TENSP
FROM THAI_SANPHAM SP
JOIN THAI_CTHD CT
ON CT.MASP = SP.MASP
JOIN THAI_HOADON HD
ON HD.SOHD = CT.SOHD
JOIN THAI_KHACHHANG KH
ON KH.MAKH = HD.MAKH
WHERE 
	KH.HOTEN = 'Nguyen Van A'
	AND YEAR(HD.NGHD) = 2006
	AND MONTH(HD.NGHD) = 10

--Câu 11
SELECT
	HD.SOHD
FROM THAI_SANPHAM SP
JOIN THAI_CTHD CT
ON CT.MASP = SP.MASP
JOIN THAI_HOADON HD
ON HD.SOHD = CT.SOHD
WHERE SP.MASP IN ('BB01','BB02')

--CÂU 12
SELECT
	HD.SOHD
FROM THAI_SANPHAM SP
JOIN THAI_CTHD CT
ON CT.MASP = SP.MASP
JOIN THAI_HOADON HD
ON HD.SOHD = CT.SOHD
WHERE SP.MASP IN ('BB01','BB02')
	AND CT.SL BETWEEN 10 AND 20

--CÂU 13
SELECT DISTINCT t1.SOHD
FROM THAI_CTHD t1
JOIN THAI_CTHD t2 ON t1.SOHD = t2.SOHD
WHERE t1.MASP = 'BB01' AND t1.SL BETWEEN 10 AND 20
  AND t2.MASP = 'BB02' AND t2.SL BETWEEN 10 AND 20;

--CÂU 14
SELECT
	SP.MASP
	,SP.TENSP
FROM THAI_SANPHAM SP
LEFT JOIN THAI_CTHD CT
ON SP.MASP = CT.MASP
WHERE CT.SL IS NULL

--CÂU 15
SELECT
    SP.MASP,
    SP.TENSP
FROM THAI_SANPHAM SP
LEFT JOIN (
    SELECT DISTINCT CT.MASP
    FROM THAI_CTHD CT
    JOIN THAI_HOADON HD ON CT.SOHD = HD.SOHD
    WHERE YEAR(HD.NGHD) = 2006
) AS SoldProducts ON SP.MASP = SoldProducts.MASP
WHERE SoldProducts.MASP IS NULL;

SELECT
    SP.MASP,
    SP.TENSP
FROM THAI_SANPHAM SP
LEFT JOIN THAI_CTHD CT ON SP.MASP = CT.MASP
LEFT JOIN THAI_HOADON HD ON HD.SOHD = CT.SOHD AND YEAR(HD.NGHD) = 2006
WHERE ct.SL IS NULL;


--CÂU 16
SELECT
    SP.MASP,
    SP.TENSP
FROM THAI_SANPHAM SP
LEFT JOIN THAI_CTHD CT ON SP.MASP = CT.MASP
LEFT JOIN THAI_HOADON HD ON HD.SOHD = CT.SOHD AND YEAR(HD.NGHD) = 2006
WHERE ct.SL IS NULL
	AND SP.NUOCSX = 'Trung Quoc'

--Câu 17
SELECT
	MAX(TRIGIA) AS CAO_NHAT,
	MIN(TRIGIA) AS THAP_NHAT
FROM THAI_HOADON

--CÂU 18
SELECT
	ROUND(AVG(TRIGIA),6) AS GIA_TRI_TRUNG_BINH
FROM THAI_HOADON
WHERE YEAR(NGHD)= 2006

--CÂU 19
SELECT
	SUM(TRIGIA) AS DOANH_THU
FROM THAI_HOADON
WHERE YEAR(NGHD)= 2006

--CÂU 20
SELECT TOP 1 SOHD, TRIGIA
FROM THAI_HOADON
WHERE YEAR(NGHD) = 2006
ORDER BY TRIGIA DESC

--CÂU 21
SELECT TOP 3
	HD.MAKH
	,KH.HOTEN
	,SUM(HD.TRIGIA) AS DOANH_SO
FROM THAI_HOADON HD
JOIN THAI_KHACHHANG KH
ON KH.MAKH = HD.MAKH
GROUP BY HD.MAKH
		,KH.HOTEN
ORDER BY DOANH_SO DESC


--CÂU 22
SELECT 
	MASP
	,TENSP
FROM THAI_SANPHAM
WHERE GIA IN (
			SELECT TOP 3 GIA
			FROM THAI_SANPHAM
			ORDER BY GIA DESC
)

--CÂU 23
SELECT 
	MASP
	,TENSP
FROM THAI_SANPHAM
WHERE GIA IN (
			SELECT TOP 3 GIA
			FROM THAI_SANPHAM
			ORDER BY GIA DESC
)
 AND NUOCSX = 'Thai Lan'


 --CÂU 24
SELECT 
	MASP
	,TENSP
FROM THAI_SANPHAM
WHERE GIA IN (
			SELECT TOP 3 GIA
			FROM THAI_SANPHAM
			WHERE NUOCSX = 'Trung Quoc'
			ORDER BY GIA DESC
)
AND NUOCSX = 'Trung Quoc'

--CÂU 25
WITH RankedCustomers AS (
    SELECT 
        MAKH, 
        HOTEN, 
        DOANHSO, 
        RANK() OVER (ORDER BY DOANHSO DESC) AS RankNum
    FROM THAI_KHACHHANG
)
SELECT 
    MAKH, 
    HOTEN, 
    DOANHSO, 
    RankNum
FROM RankedCustomers
WHERE RankNum <= 3
ORDER BY RankNum;

--CÂU 26
SELECT 
	NUOCSX,
	COUNT(MASP)	AS TONG_SAN_PHAM
FROM THAI_SANPHAM
WHERE NUOCSX = 'Trung Quoc'
GROUP BY NUOCSX

--CÂU 27
SELECT 
	NUOCSX,
	COUNT(MASP)	AS TONG_SAN_PHAM
FROM THAI_SANPHAM
GROUP BY NUOCSX

--CÂU 28
SELECT 
	NUOCSX,
	MAX(GIA) AS GIA_CAO_NHAT,
	MIN(GIA) AS GIA_THAP_NHAT,
	ROUND(AVG(GIA),2) AS GIA_TRUNG_BINH
FROM THAI_SANPHAM
GROUP BY NUOCSX

--CÂU 29
SELECT
	DAY(NGHD) AS NGAY_BAN,
	SUM(TRIGIA) AS DOANH_THU
FROM THAI_HOADON
GROUP BY DAY(NGHD)


--CÂU 30
SELECT
	MONTH(NGHD) AS THANG_BAN,
	SUM(TRIGIA) AS DOANH_THU
FROM THAI_HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)

--CÂU 31
SELECT
	CT.SOHD
FROM THAI_SANPHAM SP
JOIN THAI_CTHD CT
ON CT.MASP = SP.MASP
GROUP BY CT.SOHD
HAVING COUNT(CT.SOHD) >3

--CÂU 32
SELECT
	TOP 1 THANG
FROM(
	SELECT 
		MONTH(NGHD)	AS THANG,
		SUM(TRIGIA) AS DOANH_THU
	FROM THAI_HOADON
	WHERE YEAR(NGHD) = 2006
	GROUP BY MONTH(NGHD)
) AS DOANH_THU_THANG
ORDER BY THANG DESC


--CÂU 33
SELECT TOP 1
	SP.MASP,
	SP.TENSP
FROM THAI_SANPHAM SP
JOIN THAI_CTHD CT
ON SP.MASP = CT.MASP
JOIN THAI_HOADON HD
ON HD.SOHD = CT.SOHD
WHERE YEAR(HD.NGHD) = 2006
GROUP BY 
	SP.MASP,
	SP.TENSP
ORDER BY COUNT(CT.SL)

--CÂU 34
WITH RankedProducts AS (
    SELECT 
        MASP, 
        TENSP, 
        NUOCSX, 
        GIA,
        RANK() OVER (PARTITION BY NUOCSX ORDER BY GIA DESC) AS RankNum
    FROM THAI_SANPHAM
)
SELECT 
    MASP, 
    TENSP, 
    NUOCSX, 
    GIA
FROM RankedProducts
WHERE RankNum = 1;

--CÂU 35
SELECT NUOCSX
FROM THAI_SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3;
